name: Build iOS App
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - run: ./build.sh
      - name: Build
        uses: mxcl/xcodebuild@v1.11
        with:
          platform: "iOS"
